// THE HOMEBREW TAP'S FILES, GENERATED (PLAN.md §15.5): a cask for the app,
// one formula per extractor. Never edited by hand — the release job renders
// them from the release's SHA256SUMS and pushes them to defsquare/homebrew-tap.
//
//   node scripts/homebrew/render.mjs --version 0.1.0 --sums release/SHA256SUMS \
//        [--npm-sha256 HEX] [--release-base URL] [--out DIR]
//
// Exported for the tests; the CLI form writes Casks/codegraph.rb and
// Formula/codegraph-{java,csharp,typescript}.rb under --out.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const REPOSITORY = "https://github.com/defsquare/codegraph";
export const HOMEPAGE = REPOSITORY;

/** The release asset names the ci.yml release job writes, by RID. */
export function releaseAssets(version) {
  return {
    dmg: (rid) => `Codegraph-${version}-${rid}.dmg`,
    extractor: (name, rid) => `codegraph-${name}-${rid}`,
  };
}

/** `sha256sum` output → { name: hex }. */
export function parseSums(text) {
  const sums = {};
  for (const line of text.split("\n")) {
    const match = line.match(/^([0-9a-f]{64})\s+\*?(.+)$/);
    if (match) sums[match[2].trim()] = match[1];
  }
  return sums;
}

function sumOf(sums, asset) {
  const sha = sums[asset];
  if (sha === undefined) throw new Error(`no sha256 for ${asset} in SHA256SUMS`);
  return sha;
}

function releaseUrl(base, version, asset) {
  return `${base}/download/v${version}/${asset}`;
}

/**
 * Casks/codegraph.rb — the app plus ONE binary stanza, the single-executable
 * `codegraph` inside the bundle. Two DMGs, one per architecture.
 */
export function caskRuby({ version, sums, releaseBase = `${REPOSITORY}/releases` }) {
  const assets = releaseAssets(version);
  const arm = sumOf(sums, assets.dmg("osx-arm64"));
  const intel = sumOf(sums, assets.dmg("osx-x64"));
  return `# Generated by scripts/homebrew/render.mjs for codegraph ${version} — do not edit by hand.
cask "codegraph" do
  version "${version}"
  arch arm: "osx-arm64", intel: "osx-x64"
  sha256 arm:   "${arm}",
         intel: "${intel}"

  url "${releaseUrl(releaseBase, "#{version}", "Codegraph-#{version}-#{arch}.dmg")}"
  name "Codegraph"
  desc "Code city and dependency navigator over multi-language code models"
  homepage "${HOMEPAGE}"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates false
  depends_on macos: ">= :monterey"

  app "Codegraph.app"
  # The single-executable codegraph (CLI + daemon) that rides in the bundle.
  binary "#{appdir}/Codegraph.app/Contents/MacOS/codegraph"

  zap trash: "~/Library/Application Support/codegraph"
end
`;
}

const EXTRACTOR_DESCRIPTIONS = {
  java: "Codegraph extractor for Java (Spoon, a GraalVM native image)",
  csharp: "Codegraph extractor for C# (Roslyn, a .NET single-file binary)",
};

function className(name) {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Formula/codegraph-<name>.rb for an extractor shipped as a prebuilt binary
 * per RID: `on_macos`/`on_linux` × `on_arm`/`on_intel` blocks, each with the
 * release asset's URL and sha256; `bin.install` renames the asset to the
 * command. Legitimate in our own tap (homebrew-core refuses vendored binaries).
 */
export function binaryFormulaRuby({ name, version, sums, releaseBase = `${REPOSITORY}/releases` }) {
  const assets = releaseAssets(version);
  const block = (rid) => {
    const asset = assets.extractor(name, rid);
    return `      url "${releaseUrl(releaseBase, version, asset)}"
      sha256 "${sumOf(sums, asset)}"`;
  };
  const command = `codegraph-${name}`;
  return `# Generated by scripts/homebrew/render.mjs for codegraph ${version} — do not edit by hand.
class ${className(command)} < Formula
  desc "${EXTRACTOR_DESCRIPTIONS[name] ?? `Codegraph extractor for ${name}`}"
  homepage "${HOMEPAGE}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${block("osx-arm64")}
    end
    on_intel do
${block("osx-x64")}
    end
  end

  on_linux do
    on_arm do
${block("linux-arm64")}
    end
    on_intel do
${block("linux-x64")}
    end
  end

  def install
    # The download is the bare asset, named after its RID; the command is not.
    bin.install Dir["${command}-*"].first => "${command}"
  end

  test do
    system bin/"${command}", "--version"
    (testpath/"src").mkpath
    (testpath/"src/Hello.${name === "csharp" ? "cs" : "java"}").write "${name === "csharp" ? "class Hello { }" : "class Hello { }"}"
    system bin/"${command}", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
`;
}

/**
 * Formula/codegraph-typescript.rb — the M13 npm package on Homebrew's own
 * `node`, the shape every Node command has in Homebrew. The compiler's
 * lib files stay beside the compiler under libexec (§14.7).
 */
export function nodeFormulaRuby({ version, sha256 }) {
  return `# Generated by scripts/homebrew/render.mjs for codegraph ${version} — do not edit by hand.
class CodegraphTypescript < Formula
  desc "Codegraph extractor for TypeScript (the compiler API, no build needed)"
  homepage "${HOMEPAGE}"
  url "https://registry.npmjs.org/codegraph-typescript/-/codegraph-typescript-${version}.tgz"
  sha256 "${sha256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    system bin/"codegraph-typescript", "--version"
    (testpath/"src").mkpath
    (testpath/"src/hello.ts").write "export const hello = 1;"
    system bin/"codegraph-typescript", "--src", testpath/"src", "--out", testpath/"model.jsonl", "--progress", "none"
    assert_predicate testpath/"model.jsonl", :exist?
  end
end
`;
}

/** Every file of the tap for one release, as { relativePath: text }. */
export function renderTap({ version, sums, npmSha256, releaseBase }) {
  const files = {
    "Casks/codegraph.rb": caskRuby({ version, sums, releaseBase }),
    "Formula/codegraph-java.rb": binaryFormulaRuby({ name: "java", version, sums, releaseBase }),
    "Formula/codegraph-csharp.rb": binaryFormulaRuby({ name: "csharp", version, sums, releaseBase }),
  };
  if (npmSha256 !== undefined) {
    files["Formula/codegraph-typescript.rb"] = nodeFormulaRuby({ version, sha256: npmSha256 });
  }
  return files;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const arg = (flag) => {
    const index = process.argv.indexOf(flag);
    return index === -1 ? undefined : process.argv[index + 1];
  };
  const version = arg("--version");
  const sumsPath = arg("--sums");
  if (version === undefined || sumsPath === undefined) {
    process.stderr.write("usage: render.mjs --version X.Y.Z --sums SHA256SUMS [--npm-sha256 HEX] [--release-base URL] [--out DIR]\n");
    process.exit(2);
  }
  const out = resolve(arg("--out") ?? "tap");
  let files;
  try {
    files = renderTap({
      version,
      sums: parseSums(readFileSync(sumsPath, "utf8")),
      npmSha256: arg("--npm-sha256"),
      releaseBase: arg("--release-base"),
    });
  } catch (error) {
    // Nothing written: a tap with one blank hash would break every install.
    process.stderr.write(`render: ${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  }
  for (const [relative, text] of Object.entries(files)) {
    const path = join(out, relative);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
    process.stderr.write(`rendered ${path}\n`);
  }
  if (files["Formula/codegraph-typescript.rb"] === undefined) {
    process.stderr.write("codegraph-typescript formula not rendered: no --npm-sha256 (the npm publish did not happen)\n");
  }
}
